### PR TITLE
Added Java resources folder for Java tutorials on mxnet.io

### PR DESCRIPTION
**Pull request by piyushghai**
With reference to the PR from apache/incubator-mxnet repo : https://github.com/apache/incubator-mxnet/pull/13183 

@lanking520 @andrewfayres @aaronmarkham

### CODE REVIEW

**Comment by aaronmarkham** [comment]
Please move these under tutorials/java so that the path matches the website.
https://github.com/dmlc/web-data/tree/master/mxnet/tutorials

**Comment by piyushghai** [comment]
@aaronmarkham Updated the paths.

**Comment by ddavydenko** [comment]
@aaronmarkham , please ship it if there are no other issues with this (I personally don't see anything critical).

**Comment by nswamy** [comment]
@piyushghai Can you move this to incubator-mxnet/web-data instead?

**Comment by piyushghai** [comment]
> @piyushghai Can you move this to incubator-mxnet/web-data instead?

I can move them there, but then the instructions will have to be updated again because of the changed paths. If that's okay, I'll make this change.

**Comment by ThomasDelteil** [comment]
merging as @ddavydenko confirmed that @nswamy suggestion was not a blocker for this PR.

**Pull request merged**
