### PR TITLE
TFLite SSD model with post processing.

### PR DESCRIPTION
**Pull request by anijain2305**
@apivovarov @tqchen 
I will add a test case in TVM for TFLite frontend. There is NMS support but not tested through TFLite frontend.

The instructions are exactly same as that of 

https://github.com/dmlc/web-data/pull/186

But with post processing enabled. Thanks @apivovarov for providing the instructions.

### CODE REVIEW

**Comment by apivovarov** [comment]
Archive is 26 MB. Do you need all files from it? Can you shrink its size by removing unnecessary files?

**Comment by anijain2305** [comment]
There is only file inside - Just TFlite model

**Comment by tqchen** [comment]
is it possible to manually construct a tflite model that is smaller? e.g. do a graph cut to cut off the previous layers and only include the NMS part

**Comment by anijain2305** [comment]
I don't have experience with TF graph transforms, but it might be possible.
At the same time, I think there is value in an e2e graph testing in TVM.
Actually the other model in this directory is the same SSD model but w/o NMS. So, this model is a superset. If this model can work, we can maybe remove the previous model.

Currently, there is accuracy mismatch so we cant replace the older model. I was hoping to add this model to open an Issue so that the original authors can take a look.

**Comment by apivovarov** [comment]
yes, old file `web-data/tensorflow/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28_nopp.tgz`  (no post-processing) can be replaced with this new full model archive

**Comment by anijain2305** [comment]
@tqchen https://github.com/apache/incubator-tvm/pull/5439 is now passing, so I have removed the older TFLite file. Let me know if this is ok.

**Comment by anijain2305** [comment]
Just realized that merging this will cause failure in TVM master as the current tests are dependent on the model (*_nopp.tgz) that I am removing in this PR.

I can send a separate TVM PR that just deletes the test using *_nopp.tgz

@tqchen Wanted to check if this makes sense?

**Comment by anijain2305** [comment]
@tqchen Let me know if you need any more changes here. The TVM PR to remove old test is merged.

**Comment by anijain2305** [comment]
Ping @tqchen  :)

**Pull request merged**
