### PR TITLE
Refactor and cleanup on existing logs

### PR DESCRIPTION
**Pull request by chenw23**
This pull request

- refactors the training command file naming of [this commit](https://github.com/dmlc/web-data/commit/5d3059942a4d2f476763c879ba00dc33bc121ccf)
- cleans up the outdated training of [this commit](https://github.com/dmlc/web-data/commit/0c52f625651a84808c33fd0b53af3f402bc73a01)

### CODE REVIEW

**Comment by StrayBird-ATSH** [comment]
What about this change? 
`gluonnlp/logs/bert/finetune_XNLI-B_base_mx1.6.0rc1.sh → gluonnlp/logs/bert/finetune_XNLI_base_mx1.6.0rc1.sh`

**Comment by eric-haibin-lin** [comment]
I'm afraid not. This is also referenced in `scripts/bert/index.rst` in gluonnlp.

**Comment by StrayBird-ATSH** [comment]
Maybe a symbolic link is a good idea for solving this problem?

**Comment by StrayBird-ATSH** [comment]
`gluonnlp/logs/bert/finetune_XNLI_base_mx1.6.0rc1.log` This log is not linked anywhere. So is it OK that I change the name of this file to `gluonnlp/logs/bert/finetune_XNLI-B_base_mx1.6.0rc1.log` to be consistent with the shell script and avoid confusion?

**Comment by eric-haibin-lin** [comment]
It's used in https://raw.githubusercontent.com/dmlc/gluon-nlp/v0.9.x/scripts/bert/index.rst

**Comment by StrayBird-ATSH** [comment]
@eric-haibin-lin Do you think we should discard this pull request or we should work on some further refactor? Or keep part of this pull request?

**Comment by szha** [comment]
@eric-haibin-lin what should I do about this?

**Comment by eric-haibin-lin** [comment]
Let's keep them around for now and remove them after gluonnlp 1.0. Thanks @chenw23

**Comment by chenw23** [comment]
No problem. Look forward to that!

**Pull request closed without merging**
