### PR TITLE
add mklml 1115 build

### PR DESCRIPTION
**Pull request by glingyan**
Signed-off-by: glingyan <lingyan.guo@intel.com>

### CODE REVIEW

**Comment by piiswrong** [comment]
can we change makefile so that mkldnn always have the same path? currently you need to export LD_LIBRARY_PATH again every time mkldnn releases a new version

**Comment by glingyan** [comment]
no problem ,will do

发自我的 iPhone

在 2016年11月23日，下午2:52，Eric Junyuan Xie <notifications@github.com<mailto:notifications@github.com>> 写道：


can we change makefile so that mkldnn always have the same path? currently you need to export LD_LIBRARY_PATH again every time mkldnn releases a new version

―

**Comment by piiswrong** [comment]
merged. But please fix the path issue

**Comment by glingyan** [comment]
Hi Eric:
 Will ,I need more test
Will store in ~/mklml by default
And will ask to replace old version

发自我的 iPhone

在 2016年11月24日，上午7:00，Eric Junyuan Xie <notifications@github.com<mailto:notifications@github.com>> 写道：


merged. But please fix the path issue

―

**Pull request merged**
