### PR TITLE
[gluonnlp] add big rnn training logs

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
@szha @cgraywang

### CODE REVIEW

**Comment by cgraywang** [comment]
LGTM, thanks!

**Comment by leezu** [comment]
@eric-haibin-lin @szha

**Comment by eric-haibin-lin** [comment]
I dont have write permission. @piiswrong could you merge?

**Comment by cgraywang** [comment]
I think @hetong007 can also help to merge.

**Pull request merged**
